#!/usr/bin/env python3
"""Install an ST EdgeAI 4.x combined network_rel.bin for TikuOS."""
from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import struct

MAGIC = 0x4E49424E
HEADER_BYTES = 104
RUNTIME_VERSION = "STEdgeAI 4.0.0 / NetworkRuntime1201"


def validate(image: bytes) -> dict[str, int]:
    if len(image) < HEADER_BYTES:
        raise ValueError("network_rel.bin is shorter than the ST reloc header")
    words = struct.unpack_from("<26I", image, 0)
    if words[0] != MAGIC:
        raise ValueError("input is not an ST network_rel.bin (AI_RELOC_MAGIC)")
    flags = words[1]
    params_offset = words[12]
    if params_offset == 0:
        raise ValueError("split relocatable models are unsupported; use combined output")
    mask = 0x0FFFFFFF
    for name, value in (("text/data", words[4]), ("bss", words[6]),
                        ("rel", words[10])):
        if (value & mask) > len(image):
            raise ValueError(f"ST {name} section exceeds input length")
    rel_start = words[9] & mask
    rel_end = words[10] & mask
    if rel_start > rel_end or rel_end > len(image) or (rel_end - rel_start) % 4:
        raise ValueError("ST relocation section has invalid geometry")
    for at in range(rel_start, rel_end, 4):
        site = struct.unpack_from("<I", image, at)[0]
        if (site & 0xF0000000) not in (0x20000000, 0x40000000):
            raise ValueError(f"ST relocation site at 0x{at:x} has invalid address class")
        if (site & mask) > len(image) - 4:
            raise ValueError(f"ST relocation site at 0x{at:x} exceeds input length")
    if ((flags >> 28) & 0xF, (flags >> 24) & 0xF) != (8, 0):
        raise ValueError("network_rel.bin was built for an incompatible reloc runtime")
    if not flags & (1 << 21):
        raise ValueError("network_rel.bin lacks LL_ATON_EB_DBG_INFO metadata")
    if not flags & (1 << 22):
        raise ValueError("network_rel.bin is not an asynchronous LL-ATON model")
    return {"bytes": len(image), "flags": flags, "params_offset": params_offset}


def c_array(image: bytes, symbol: str) -> str:
    values = ", ".join(f"0x{b:02x}" for b in image)
    return ("/* Generated by stm32n6_relpack.py; source bytes are unchanged. */\n"
            "#include <stdint.h>\n"
            f"const uint8_t {symbol}[] __attribute__((aligned(8), used)) = {{\n"
            f"    {values}\n}};\n"
            f"const uint32_t {symbol}_len = {len(image)}u;\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=pathlib.Path)
    parser.add_argument("--output-root", type=pathlib.Path, default=pathlib.Path("data/npu"))
    parser.add_argument("--name")
    parser.add_argument("--c-array", type=pathlib.Path)
    parser.add_argument("--symbol", default="tiku_npu_network_rel")
    args = parser.parse_args()
    image = args.input.read_bytes()
    metadata = validate(image)
    name = args.name or args.input.name
    if pathlib.PurePosixPath(name).name != name or not name.endswith(".bin"):
        raise SystemExit("--name must be a single .bin filename")
    args.output_root.mkdir(parents=True, exist_ok=True)
    destination = args.output_root / name
    shutil.copyfile(args.input, destination)
    manifest = dict(metadata, runtime=RUNTIME_VERSION, model=name,
                    namespace="/data/npu/", mode="COPY", split=False)
    (args.output_root / (name + ".manifest.json")).write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    if args.c_array:
        args.c_array.parent.mkdir(parents=True, exist_ok=True)
        args.c_array.write_text(c_array(image, args.symbol), encoding="utf-8")
    print(f"{destination} -> /data/npu/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
